[package]
name = "llvm2"
version = "0.1.0"
authors = ["valentine-mario <valentine13400@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
docopt = "1"
serde = { version = "1", features = ["derive"] }
rustc-serialize = "0.3"
